server:
  port: 8080

spring:
  jpa:
    show-sql: true
      properties:
        javax:
          persistence:
            sharedCache:
              mode: ENABLE_SELECTIVE

    hibernate:
      ddl: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      format_sql: true
      generate_statistics: true
      cache:
        use_second_level_cache: true
        use_query_cache: true
        region:
          factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: password
